name: Bedwars
version: 2.3
api:
- 1.14.0
- 2.0.0
main: Bluplayz\Bedwars
author: 
 - Bluplayz
 - MrKiAN
website: http://youtube.com/Bluplayz
commands:
    Bedwars:
        description: Bedwars Main Command
        aliases: [BW]
    Start:
        description: Bedwars Forcestart Command
